name: Deploy to 123host via FTP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Đẩy thẳng vào thư mục web chính thức
          server-dir: domains/tranhoangdao.id.vn/public_html/

          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/vendor/**
            storage/**
            .env
            vendor.zip
            *.docx
            public/storage
